version: '3'
services:
  app:
    image: ubuntu
    container_name: ubuntu
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/home/public
    user: root
    working_dir: /home/public
    tty: true
    stdin_open: true

  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: IB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
